/*
 * MediaPanel1.java
 *
 * Created on __DATE__, __TIME__
 */

package com.media;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.net.URL;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.swing.JPanel;

/**
 *
 * @author  __USER__
 */
public class MediaPanel1 extends javax.swing.JPanel {

	/** Creates new form MediaPanel1 */
	public MediaPanel1() {
		initComponents();
	}
	 public MediaPanel1( URL mediaURL )
  	 {
     	 setLayout( new BorderLayout() ); // use a BorderLayout

     	 // Use lightweight components for Swing compatibility
	 Manager.setHint( Manager.LIGHTWEIGHT_RENDERER, true );
    
    	 try
    	 {
        	 // create a player to play the media specified in the URL
        	 Player mediaPlayer = Manager.createRealizedPlayer( mediaURL );

        	 // get the components for the video and the playback controls
        	 Component video = mediaPlayer.getVisualComponent();
       	 Component controls = mediaPlayer.getControlPanelComponent();
       
       	 if ( video != null )
           	 add( video, BorderLayout.CENTER ); // add video component

        	 if ( controls != null )
           	 add( controls, BorderLayout.SOUTH ); // add controls

        	 mediaPlayer.start(); // start playing the media clip
     	 } // end try
     	 catch ( NoPlayerException noPlayerException )
     	 {
        	 System.err.println( "No media player found" );
     	 } // end catch
     	 catch ( CannotRealizeException cannotRealizeException )
	 {
        	 System.err.println( "Could not realize media player" );
     	 } // end catch
     	 catch ( IOException iOException )
   {
        	 System.err.println( "Error reading from the source" );
     	 } // end catch
      } // end MediaPanel constructor
	 // end class MediaPanel


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}