/*
 * AddCodePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.toolkit;

/**
 *
 * @author  __USER__
 */
public class AddCodePanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form AddCodePanel */
	private int count = 0;

	public String toString() {
		return "code-" + (++count);
	}

	public AddCodePanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		enterCodeLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		codeEditorPane = new javax.swing.JEditorPane();
		jSeparator1 = new javax.swing.JSeparator();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		autoSelectOnDelClick = new javax.swing.JCheckBox();

		setBackground(new java.awt.Color(153, 153, 153));

		enterCodeLabel.setText("enter code");

		codeEditorPane.setFont(new java.awt.Font("Courier New", 0, 11));
		jScrollPane1.setViewportView(codeEditorPane);

		jButton1.setText("/\\");

		jButton2.setText("\\/");

		jButton3.setText("X");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		autoSelectOnDelClick.setVisible(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(enterCodeLabel)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										233, Short.MAX_VALUE)
								.addComponent(autoSelectOnDelClick)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton3))
				.addComponent(jSeparator1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 451,
						Short.MAX_VALUE)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 451,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton3)
												.addComponent(jButton2)
												.addComponent(jButton1)
												.addComponent(enterCodeLabel)
												.addComponent(
														autoSelectOnDelClick))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										161,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		//delete code
		AddContentPage cp = (AddContentPage) (getParent().getParent()
				.getParent().getParent().getParent().getParent().getParent());

		//= new AddContentPage();
		System.out.println("start delete method form addtextJPanel");
		autoSelectOnDelClick.setSelected(true);
		cp.removeTextPanel();
		System.out.println("selection done auto "
				+ autoSelectOnDelClick.isSelected());

		System.out.println("end delete method form addtextJPanel");
		this.validate();

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JCheckBox autoSelectOnDelClick;
	public javax.swing.JEditorPane codeEditorPane;
	private javax.swing.JLabel enterCodeLabel;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;

	// End of variables declaration//GEN-END:variables
	public boolean isSelected() {
		System.out.println(autoSelectOnDelClick.isSelected() + " in AddText");
		return autoSelectOnDelClick.isSelected();
	}

	public String getText() {
		return codeEditorPane.getText();
	}

	public void setText(String value) {
		// TODO Auto-generated method stub
		codeEditorPane.setText(value);
	}

}