/*
 * Txtbox.java
 *
 * Created on __DATE__, __TIME__
 */

package com.toolkit;

/**
 *
 * @author  __USER__
 */
public class Txtbox extends javax.swing.JPanel {

	/** Creates new form Txtbox */
	public Txtbox() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		addPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jButton1 = new javax.swing.JButton();

		addPanel.setBackground(new java.awt.Color(0, 153, 153));

		jLabel1.setText("GVRTBFE");

		jCheckBox1.setText("checkToDelete");
		jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jCheckBox1StateChanged(evt);
			}
		});

		jButton1.setText("Click");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(
				addPanel);
		addPanel.setLayout(addPanelLayout);
		addPanelLayout
				.setHorizontalGroup(addPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								addPanelLayout.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addContainerGap(311, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								addPanelLayout
										.createSequentialGroup()
										.addContainerGap(206, Short.MAX_VALUE)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBox1)));
		addPanelLayout
				.setVerticalGroup(addPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								addPanelLayout
										.createSequentialGroup()
										.addGroup(
												addPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBox1)
														.addComponent(jButton1))
										.addGap(4, 4, 4).addComponent(jLabel1)
										.addContainerGap(233, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(addPanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(addPanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println("in auto select mode");
		jCheckBox1.setSelected(true);
		this.validate();
	}

	private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {
		CheckBoxEx del = new CheckBoxEx();
		System.out.println(jCheckBox1.isSelected() + " selected or not");
		System.out.println("CAlling remove method");
		del.removeMethod();
		this.validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel addPanel;
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;

	// End of variables declaration//GEN-END:variables
	public boolean isSelected() {
		// TODO Auto-generated method stub
		System.out.println("Check box selected " + jCheckBox1.isSelected());
		return jCheckBox1.isSelected();
	}

}